### ISSUE TITLE
uhf.py file in Python examples is missing references

### ISSUE THREAD

**Issue by gregarican** [sbcshop/UHF_Lite_HAT_Software#2]
Trying to invoke the Python command uhf.setRegion_US() results in an error. Since the write_tag parameter in the setRegion_US() method isn't defined.

See below for the section of the uhf.py file that I'm referring to:

` def setRegion_US(self):
        data = self.send_command([STARTBYTE, write_tag, ENDBYTE])
        time.sleep(0.5)
        rec_data = self.serial.read(24)
        #print(rec_data)`

Any suggestions? Since I will need to tweak a few settings, such as transmit power and others, this uhf.py file needs to be complete. In this case, the file comments indicate that setting the region will increase the read range. This is important, since with the region commented out the read range is maybe just around half a meter or less.

**Comment by gregarican** [comment]
Based on the user manual, I believe the proper command to send the device would be defined as:

`SET_REGION_US ='0700010210'`

So modifying this in the setRegion_US() method, I wind up with:

`def setRegion_US(self):
        data = self.send_command([STARTBYTE, SET_REGION_US, ENDBYTE])
        time.sleep(0.5)
        rec_data = self.serial.read(24)
        #print(rec_data)`

This still doesn't seem to focus the frequency spectrum, since the read range is still rather limited.

**Comment by gregarican** [comment]
Closing this. Decompiling the Visual Studio executable I set the region using that app. And see the command that needs to be sent is BB 00 07 00 01 02 0A 7E.

**Comment by sbcshop3** [comment]
Uhf library file updated to facilitate region selection, try now

**Comment by gregarican** [comment]
Yes, that works now. Thanks for this. Now trying to use the OLED function based on your example script, this also fails. I have ensured that pillow and SMBus are both pip-installed for my Python 3 environment. The error specifics state:

“Traceback (most recent call last):
  File "/home/diamondcellar/Downloads/uhf_multiple_read.py", line 19, in <module>
    display = SSD1306()
              ^^^^^^^^^
  File "/home/diamondcellar/Downloads/oled_091.py", line 87, in __init__
    i2c_interface.__init__(self, address=address)
  File "/home/diamondcellar/Downloads/oled_091.py", line 52, in __init__
    self.bus = SMBus(self.bus_id())
               ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function i2c_interface.__del__ at 0x7fa4f76700>
Traceback (most recent call last):
  File "/home/diamondcellar/Downloads/oled_091.py", line 56, in __del__
    self.close_i2c()
  File "/home/diamondcellar/Downloads/oled_091.py", line 59, in close_i2c
    self.bus.close()
    ^^^^^^^^
AttributeError: 'SSD1306' object has no attribute 'bus'”

Any insight into this as well?
Greg Kujawa
IT Manager

DIAMOND CELLAR Holdings, LLC
6280 Sawmill Road
Dublin, OH 43017
614-923-9515 phone
614-336-4555 fax
www.diamondcellar.com<http://www.diamondcellar.com>
Office Hours: M Tu W Th F



CONFIDENTIALITY NOTICE
UNAUTHORIZED INTERCEPTION IS PROHIBITED BY FEDERAL LAW
[Electronic Communications Privacy Act of 1986, 18 U.S.C. 2701(a) and 2702(a)] This message is protected by Constitutional Rights and applicable legal privileges.  It is strictly confidential.

**Comment by gregarican** [comment]
Disregard, as I see now that I needed to enable i2c communication in the RPi interface settings. Works fine now!

Greg Kujawa
IT Manager

DIAMOND CELLAR Holdings, LLC
6280 Sawmill Road
Dublin, OH 43017
614-923-9515 phone
614-336-4555 fax
www.diamondcellar.com<http://www.diamondcellar.com>
Office Hours: M Tu W Th F



CONFIDENTIALITY NOTICE
UNAUTHORIZED INTERCEPTION IS PROHIBITED BY FEDERAL LAW
[Electronic Communications Privacy Act of 1986, 18 U.S.C. 2701(a) and 2702(a)] This message is protected by Constitutional Rights and applicable legal privileges.  It is strictly confidential.


From: Kujawa, Greg
Sent: Tuesday, May 21, 2024 8:16 AM
To: 'sbcshop/UHF_Lite_HAT_Software' ***@***.***>; sbcshop/UHF_Lite_HAT_Software ***@***.***>
Cc: State change ***@***.***>
Subject: RE: [sbcshop/UHF_Lite_HAT_Software] uhf.py file in Python examples is missing references (Issue #2)

Yes, that works now. Thanks for this. Now trying to use the OLED function based on your example script, this also fails. I have ensured that pillow and SMBus are both pip-installed for my Python 3 environment. The error specifics state:

“Traceback (most recent call last):
  File "/home/diamondcellar/Downloads/uhf_multiple_read.py", line 19, in <module>
    display = SSD1306()
              ^^^^^^^^^
  File "/home/diamondcellar/Downloads/oled_091.py", line 87, in __init__
    i2c_interface.__init__(self, address=address)
  File "/home/diamondcellar/Downloads/oled_091.py", line 52, in __init__
    self.bus = SMBus(self.bus_id())
               ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function i2c_interface.__del__ at 0x7fa4f76700>
Traceback (most recent call last):
  File "/home/diamondcellar/Downloads/oled_091.py", line 56, in __del__
    self.close_i2c()
  File "/home/diamondcellar/Downloads/oled_091.py", line 59, in close_i2c
    self.bus.close()
    ^^^^^^^^
AttributeError: 'SSD1306' object has no attribute 'bus'”

Any insight into this as well?
Greg Kujawa
IT Manager

DIAMOND CELLAR Holdings, LLC
6280 Sawmill Road
Dublin, OH 43017
614-923-9515 phone
614-336-4555 fax
www.diamondcellar.com<http://www.diamondcellar.com>
Office Hours: M Tu W Th F



CONFIDENTIALITY NOTICE
UNAUTHORIZED INTERCEPTION IS PROHIBITED BY FEDERAL LAW
[Electronic Communications Privacy Act of 1986, 18 U.S.C. 2701(a) and 2702(a)] This message is protected by Constitutional Rights and applicable legal privileges.  It is strictly confidential.

**Comment by sbcshop3** [comment]
That's great.

**Comment by gregarican** [comment]
Last question. Overall I am set with this now for our purposes. But was wondering if there is the ability to install an antenna of some sort to increase the read range a bit?

Greg Kujawa
IT Manager

DIAMOND CELLAR Holdings, LLC
6280 Sawmill Road
Dublin, OH 43017
614-923-9515 phone
614-336-4555 fax
www.diamondcellar.com<http://www.diamondcellar.com>
Office Hours: M Tu W Th F



CONFIDENTIALITY NOTICE
UNAUTHORIZED INTERCEPTION IS PROHIBITED BY FEDERAL LAW
[Electronic Communications Privacy Act of 1986, 18 U.S.C. 2701(a) and 2702(a)] This message is protected by Constitutional Rights and applicable legal privileges.  It is strictly confidential.

**Comment by sbcshop3** [comment]
Please connect with our development team they have customize solution to achieve increase range as per your requirement.
